name: Build and Pulish @meterexhq/meld

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Clean install dependencies
        run: npm ci
      - name: Bump meld-tailwind version (patch)
        run: npm --no-git-tag-version version patch
      - name: Commit meld-tailwind version (patch)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "[skip-ci] bump library version"
          commit_options: "--no-verify --signoff"
          commit_author: Github Actions <actions@github.com>
      - name: Build meld-tailwind
        run: npm run build

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish:
    permissions:
      contents: read
      packages: write
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: npm publish
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
